// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddScreenNames(arg1:string):Promise<number>;

export function DeleteScreenName(arg1:string):Promise<void>;

export function GetAllScreenNames():Promise<Array<app.ScreenNameItem>>;

export function GetConfig():Promise<app.ConfigData>;

export function GetInitError():Promise<string>;

export function IsScanning():Promise<boolean>;

export function OpenConfigDir():Promise<void>;

export function RunOnce():Promise<void>;

export function SaveConfig(arg1:app.ConfigData):Promise<void>;

export function StartScan():Promise<void>;

export function StopScan():Promise<void>;
