// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScreenNames(arg1) {
  return window['go']['app']['App']['AddScreenNames'](arg1);
}

export function DeleteScreenName(arg1) {
  return window['go']['app']['App']['DeleteScreenName'](arg1);
}

export function GetAllScreenNames() {
  return window['go']['app']['App']['GetAllScreenNames']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetInitError() {
  return window['go']['app']['App']['GetInitError']();
}

export function IsScanning() {
  return window['go']['app']['App']['IsScanning']();
}

export function OpenConfigDir() {
  return window['go']['app']['App']['OpenConfigDir']();
}

export function RunOnce() {
  return window['go']['app']['App']['RunOnce']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function StartScan() {
  return window['go']['app']['App']['StartScan']();
}

export function StopScan() {
  return window['go']['app']['App']['StopScan']();
}
